version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    ports:
      - '8080:8080'
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: